### PR TITLE
add hashes

### PR DESCRIPTION
**Pull request by moonshadow565**
generated by dumping strings from executables and demangling any symbol names found
used a simple regex to extract words: ``(?:[a-zA-Z0-9]+_?)+[a-zA-Z0-9]+``
unfiltered .txt containing source strings can be found here: https://mega.nz/#!u90xQaDI!u7tbR64jZNqKuhl1NA_Jzkga1KbkC3yGAlnuIYCnWN8

### CODE REVIEW

**Comment by benoitryder** [comment]
The diff removes 3 hashes from `hashes.binfields.txt`. I assume it's not intended?

**Comment by moonshadow565** [comment]
Its removed because it seems a duplicate sliped through before :)
https://github.com/CommunityDragon/CDTB/blob/master/cdragontoolbox/hashes.binfields.txt#L50
https://github.com/CommunityDragon/CDTB/blob/master/cdragontoolbox/hashes.binfields.txt#L639

**Comment by moonshadow565** [comment]
This commit: https://github.com/CommunityDragon/CDTB/commit/d580e7e69e4c9c4b23ff71062c18a48b163afe0c#diff-c0b3f92d9d53dbca557e1f9e841eb15d

**Comment by benoitryder** [comment]
Indeed. Good catch.

**Pull request merged**
